// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATQASYt_I5mZbbw3BEKUoRXwiDYJZn9u0',
    appId: '1:647182178399:web:e7a914b653a76df226a3ea',
    messagingSenderId: '647182178399',
    projectId: 'org4niz4t3',
    authDomain: 'org4niz4t3.firebaseapp.com',
    storageBucket: 'org4niz4t3.firebasestorage.app',
    measurementId: 'G-2MFX57RSMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ62Xs7Cofr-psdVWTDETb7CwqErztXfg',
    appId: '1:647182178399:android:9b2857000ba9a5f626a3ea',
    messagingSenderId: '647182178399',
    projectId: 'org4niz4t3',
    storageBucket: 'org4niz4t3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACbGxLVdvHWA40o-Le2sYbtTGFO8ns31o',
    appId: '1:647182178399:ios:eb355c712475465326a3ea',
    messagingSenderId: '647182178399',
    projectId: 'org4niz4t3',
    storageBucket: 'org4niz4t3.firebasestorage.app',
    iosBundleId: 'com.example.organiz4t3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACbGxLVdvHWA40o-Le2sYbtTGFO8ns31o',
    appId: '1:647182178399:ios:eb355c712475465326a3ea',
    messagingSenderId: '647182178399',
    projectId: 'org4niz4t3',
    storageBucket: 'org4niz4t3.firebasestorage.app',
    iosBundleId: 'com.example.organiz4t3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATQASYt_I5mZbbw3BEKUoRXwiDYJZn9u0',
    appId: '1:647182178399:web:91456cb792c7c72626a3ea',
    messagingSenderId: '647182178399',
    projectId: 'org4niz4t3',
    authDomain: 'org4niz4t3.firebaseapp.com',
    storageBucket: 'org4niz4t3.firebasestorage.app',
    measurementId: 'G-5TXMK0JLZT',
  );

}